### ISSUE TITLE
Segfault in ChunkWriter<1024u, 10u>::drop

### ISSUE THREAD

**Issue by bsdb0y** [ShamanDBI/shaman-core#2]
The "scripts" directory mentioned in the documentation is missing, so I believe there might be a typo.
https://shamandbi.github.io/shaman-core/getting_started.html
![image](https://github.com/user-attachments/assets/9857ee56-1abb-40b9-9edb-5e81ddc9f1fb)

```
cat script/run.sh 
eagle_coverage_app/eagle_coverage -l app.log --cov-basic-block ./test_prog_1.bb --pipe-id 51966 -e ./test_target/bin/test_target 1
```
I couldn't find `eagle_coverage_app/eagle_coverage`, so I assumed that `builds/binary_coverage_app/binary_coverage` might be the equivalent binary. After using it with the same arguments, I encountered a segmentation fault, which seems to be caused by a `nullptr deref`.

Crash log:

```
Program received signal SIGSEGV, Segmentation fault.
0x00000000004da38a in ChunkWriter<1024u, 10u>::drop (this=0x0) at /home/test/shamanDBI/bsdb0y/shaman-core/include/mempipe.hpp:168
168	        uint8_t *buffer = m_shm_raw_buffer;
(gdb) bt
#0  0x00000000004da38a in ChunkWriter<1024u, 10u>::drop (this=0x0) at /home/test/shamanDBI/bsdb0y/shaman-core/include/mempipe.hpp:168
#1  0x00000000004d9a41 in CoverageTraceWriter::write_module_info (this=0x6c1570)
    at /home/test/shamanDBI/bsdb0y/shaman-core/src/coverage_trace_writer.cpp:41
#2  0x00000000004d536b in BreakpointReader::next (this=0x7fffffffcc70) at /home/test/shamanDBI/bsdb0y/shaman-core/src/breakpoint_reader.cpp:85
#3  0x00000000004093c6 in parser_basic_block_file(Debugger&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool, std::shared_ptr<CoverageTraceWriter>) ()
#4  0x000000000040a613 in main ()
(gdb) 

```

![image](https://github.com/user-attachments/assets/b9b0ed52-6e0e-4ae9-82ba-a78035edd6d2)

It appears that `rax` is `null` which getting assigned from `rdi`, which means passed as an argument to `drop`. This seems to be the `this` pointer, and the issue might be related to it.

**Comment by 0xd3xt3r** [comment]
You can find the documentation about how to build and the example on this linke https://shamandbi.github.io/building.html#example-2-binary-code-coverage
